### ISSUE TITLE
What license is the project?

### ISSUE THREAD

**Issue by ruzko** [Jimbwlah/tensorflow-ring-animal-detector#1]
Hi!

This is neat stuff.
If I'd been aware of this when I started [my own project](https://gitlab.com/papiris/predator-detect-and-notify), I'd probably have based it on your code :)

I'm actually doing my bachelor's thesis now, with the goal of implementing privacy and freedom-respecting camera surveillance, predator detection, alert and repel; in livestock farming.
A major premise of the thesis is that the code should be AGPL-v3-or-later, to make sure that people throughout the user/developer chain have access to the source code.

Since your project doesn't declare a license at the moment, I believe [it's currently considered public-source proprietary](https://choosealicense.com/no-permission/)

I'd love to consider your code among the alternatives to base the thesis work on (and contribute to!), but it'd need to be under an AGPL-v3 compatible license :)

I see the Tensorflow code you've included is Apache-2.0, which is AGPL-v3 compatible.
Other AGPL-v3 compatible licenses [include MIT, MPL-2.0 and BSD (2&3-clause).](https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility)

I hope you'll consider this, and add a compatible license :slightly_smiling_face: 

Best,
Jacob

**Comment by Jimbwlah** [comment]
Hey,

Please feel free to use this as you please!

Thanks

**Comment by ruzko** [comment]
Thanks, I'm glad to hear that! :raised_hands:
